

apiVersion: v1
kind: Pod
metadata:
  labels:
    test: share-pod
  name: share-pod
spec:
  volumes:
  - name: host-volume
    hostPath:
      path: /home/docker/pod-volume # Path needs to be a directoy existing on Worker node running the Pod
  containers:
  # Nginx Webserver mounting the created volume 
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html # Where to mount volume inside of container
      name: host-volume # Name of the created volume 
  # A second container which mounts the same volume and fills it with a file
  - image: debian
    name: debian
    volumeMounts:
    - mountPath: /host-vol
      name: host-volume
    command: ["/bin/sh", "-c", "echo I like shared volumes > /host-vol/index.html; sleep 3600;"]