
# THIS IS NOT A VALID YAML FILE. IT ONLY CONTAINS EXAMPLES SNIPPETS

# Inside a Container, we can retrieve the key-value data of an entire ConfigMap or the values of specific ConfigMap keys as environment variables.
# In the following example all the myapp-full-container Container's environment variables receive the values of the full-config-map ConfigMap keys:
# ...
  containers:
  - name: myapp-full-container
    image: myapp
    envFrom:
    - configMapRef:
      name: full-config-map
# ...

# In the following example the myapp-specific-container Container's environment variables receive their
# values from specific key-value pairs from two separate ConfigMaps, config-map-1 and config-map-2:
# ...
  containers:
  - name: myapp-specific-container
    image: myapp
    env:
    - name: SPECIFIC_ENV_VAR1
      valueFrom:
        configMapKeyRef:
          name: config-map-1
          key: SPECIFIC_DATA
    - name: SPECIFIC_ENV_VAR2
      valueFrom:
        configMapKeyRef:
          name: config-map-2
          key: SPECIFIC_INFO
# ...

# As Volumes

# We can mount a vol-config-map ConfigMap as a Volume inside a Pod. For each key in the ConfigMap, a file
# gets created in the mount path (where the file is named with the key name) and the content of that file
# becomes the respective key's value:
# ...
  containers:
  - name: myapp-vol-container
    image: myapp
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
  volumes:
  - name: config-volume
    configMap:
      name: vol-config-map
# ...